services:
    _defaults:
        autoconfigure: true
    Kreativsoehne\Cookieconsent\Controller\FrontendModule\CookieconsentController:

    Kreativsoehne\Cookieconsent\Controller\ContentElement\ToogleCookieconsentController:

    Kreativsoehne\Cookieconsent\Migration\Version4\CategoryMigration:
        arguments:
            - '@database_connection'

    Kreativsoehne\Cookieconsent\Migration\Version4\ServiceMigration:
        arguments:
            - '@database_connection'
